# Generated by Django 3.0.8 on 2020-07-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_profiler_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiler',
            name='profile_url',
            field=models.CharField(blank=True, default='https://miro.medium.com/proxy/1*VcHVCyRSAOF3V6Ldi0iXOQ.jpeg', max_length=254),
        ),
    ]
