# Generated by Django 3.0.8 on 2020-07-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_auto_20200726_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiler',
            name='dob',
            field=models.CharField(max_length=64),
        ),
    ]
